name: Deploy to GitHub Pages

on:
  push:
    branches:
      - hugo

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - name: commit and push to hugo branch
        run: |
          git clone https://github.com/gpQ4utjefs/gpq4utjefs.github.io.git
          cd gpq4utjefs.github.io.git
          ls
