name: Deploy to GitHub Pages

on:
  push:
    branches:
      - obsidian

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - name: commit and push to hugo branch
        run: |
          git clone --branch hugo https://github.com/gpQ4utjefs/gpq4utjefs.github.io.git
          cd gpq4utjefs.github.io
          pwd
          ls
          rm -r .git
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: /home/runner/work/gpq4utjefs.github.io/gpq4utjefs.github.io/gpq4utjefs.github.io