name: Deploy to GitHub Pages

on:
  push:
    branches:
      - obsidian

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - name: commit and push to hugo branch
        run: |
          git clone --branch hugo https://github.com/gpQ4utjefs/gpq4utjefs.github.io.git
          cd gpq4utjefs.github.io
          pwd
      - name: Deploy.
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: /home/runner/work/gpq4utjefs.github.io/gpq4utjefs.github.io/gpq4utjefs.github.io
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}