name: Deploy to GitHub Pages

on:
  push:
    branches:
      - obsidian

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: commit and push to hugo branch
        run: |
          git clone --branch hugo https://github.com/gpQ4utjefs/gpq4utjefs.github.io.git
          cd gpq4utjefs.github.io
          pwd
          ls
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - name: checking current directory
        run: |
          cd /home/runner/work/gpq4utjefs.github.io/gpq4utjefs.github.io/gpq4utjefs.github.io
          ls
      - name: Push to gh-pages branch --force
        # You may pin to the exact commit or the version.
        # uses: ftnext/action-push-ghpages@621f3b2f1d34079b4da6051daedb3e200af0dd38
        uses: ftnext/action-push-ghpages@v1.0.0
        with:
          # Path to the directory where the static assets are located.
          build_dir: /home/runner/work/gpq4utjefs.github.io/gpq4utjefs.github.io/gpq4utjefs.github.io
          # Create github token in repo/settings/secrets/actions with name GithubToken
          github_token: ${{ secrets.GITHUB_TOKEN }}