name: Deploy to GitHub Pages

on:
  push:
    branches:
      - obsidian

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - name: commit and push to hugo branch
        run: |
          git clone --branch hugo https://github.com/gpQ4utjefs/gpq4utjefs.github.io.git
          cd gpq4utjefs.github.io
          rm -r .git
          cd content
          git clone --branch obsidian https://github.com/gpQ4utjefs/gpq4utjefs.github.io.git
          cd gpq4utjefs.github.io
          rm -r .git .github
          cd ..
          mv gpq4utjefs.github.io/* .
          rm -r gpq4utjefs.github.io
      - uses: actions/setup-python@v4 
        with:
          python-version: 'pypy3.9' 
      - run: python script.py
      - name: Deploy.
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: /home/runner/work/gpq4utjefs.github.io/gpq4utjefs.github.io/gpq4utjefs.github.io
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}